### ISSUE TITLE
predefined git user variables in 3.0-rc

### ISSUE THREAD

**Issue by alfert** [tknerr/bills-kitchen#103]
After download, unzip, mount and first start of conemu, the git user name and the email address are set to your name. Would be nice, if they would be blank and/or some hint how set them properly during install.

Cheers, Klaus.

**Comment by tknerr** [comment]
Oh that is a bug indeed!

Should have actually happened while the rc package was created as per this:
https://github.com/tknerr/bills-kitchen/blob/master/Rakefile#L196-203

Have to doublecheck whether the above doesn't work or I messed it up because I was working inside that directory while it was still zipping... ;-)

**Comment by tknerr** [comment]
The packaging works fine. 3.0-rc4 will have the git use correctly reset again. Thanks for reporting!
